### PR TITLE
Fix functional tests

### PR DESCRIPTION
**Pull request by rgildein**
- switch branch to main for actions-operator
- using channel candidate for docker-snap, due [1]
- switch to charmhub charm names
- remove temporary fix for python-libjuju issues #568 #223

---
[1]: https://github.com/docker-snap/docker-snap/issues/45

### CODE REVIEW

**Review by addyess — APPROVED** [review]
I've pulled these changes and the integration tests can't run as the model doesn't come up cleanly. I'm not saying it necessarily is a result of these changes, just trying to be clear.

Otherwise, I see nothing wrong with this PR

**Comment by rgildein** [comment]
> I've pulled these changes and the integration tests can't run as the model doesn't come up cleanly. I'm not saying it necessarily is a result of these changes, just trying to be clear.
> 
> Otherwise, I see nothing wrong with this PR

Thank you for the review, I hold it because I waited for the python-libjuju 2.9.5 to come out.

**Comment by addyess** [comment]
@r-f-g could you rebase with the master branch?  I was able to get the integration tests after doing this

Running the integration tests, the charm fails to resolve because of changes around [`configure_cni`](https://github.com/charmed-kubernetes/charm-flannel/blob/master/reactive/flannel.py#L69-L74) due to changes in dependent libraries  (see https://github.com/charmed-kubernetes/charm-flannel/pull/74)

**Comment by rgildein** [comment]
@addyess I rebase it w/ master, however the functional test still don't work. I found [PR#186](https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/186), so I changed the channel to `1.23/edge` but it didn't help either.

cdk-master still reports an error `Waiting for 3 kube-system pods to start`. All pods have a single event `Warning  FailedScheduling  115s (x41 over 42m)  default-scheduler  no nodes available to schedule pods`.

**Comment by addyess** [comment]
I ran the integration tests with your commit at e6b46b7 and had ALMOST totally successful test run. [integration-logs](https://paste.ubuntu.com/p/j44bQchYdt/) on vSphere host. It seems to indicate the test `test_change_cidr_network` when it restarts the `kubernetes-worker` machine, `sudo reboot now` returns an rc=1 instead of the expected `0 or 255`.  

I'll be running the tests again with `tox -e integration -- --keep-models` to see if i can narrow in on why this test fails.
I haven't tried the commit c1ee01b yet.

**Comment by addyess** [comment]
I found that if i update `test_change_cidr_network(...)` like this:

```python
    rc, stdout, stderr = await ops_test.juju(
        "ssh", "-m", ops_test.model_full_name, f"{k8s_worker.name}",
        "--", "sudo su root -c '(sleep 5; reboot) &'"
    )
    assert rc == 0, ("Failed to restart kubernetes-worker with "
                     f"resource: {stderr or stdout}")
```

the tests are passing successfully.  This backgrounds the reboot in 5 seconds from now, and returns `rc=0` immediately

**Comment by addyess** [comment]
@r-f-g , i'm seeing passing results with the commit c1ee01b and the above changes to the test.

I don't think your changes in this PR should be blocked by this if you can get the above test changes in

**Comment by rgildein** [comment]
@addyess, thanks for testing it out. I changed the restart kubernetes-worker unit as you suggested.
Running a functional test in LXD was more of a temporary solution and I believe we should move it to vSphere in the future.

**Comment by addyess** [comment]
Yes, i ran all my functional tests on vSphere.  I'll give this one more go and merge on success.

**Comment by addyess** [comment]
@r-f-g .  I'm going to merge this one and immediately open another PR with changes i had to make to `test_change_cidr_network` test so you can get out of this loop.  I've got the tests running successfully and consistently.

**Pull request merged**
